app:
    resource: "@AppBundle/Resources/config/routing_rest.yml"
    type:     rest

nelmio_api_doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   api/doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"